pvc_cidr_block    = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
availability_zone = "eu-north-1a"
environment       = "dev"
instance_type     = "t3.micro"
public_key_path   = "/home/hw-ubuntu/.ssh/id_rsa.pub"
