apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  labels:
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/part-of: kafka-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: schema-registry
  ports:
    - name: http
      port: 8081
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  labels:
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/part-of: kafka-lab
spec:
  replicas: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: schema-registry

  template:
    metadata:
      labels:
        app.kubernetes.io/name: schema-registry
        app.kubernetes.io/part-of: kafka-lab

    spec:
      # Important for Confluent containers on Kubernetes.
      # Prevents Kubernetes from injecting:
      # SCHEMA_REGISTRY_PORT=tcp://...
      enableServiceLinks: false

      terminationGracePeriodSeconds: 30

      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:8.3.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8081
              protocol: TCP

          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry

            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081

            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://lab-kafka-kafka-bootstrap:9092

            - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
              value: PLAINTEXT

            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
              value: _schemas

            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR
              value: "3"

            - name: SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL
              value: BACKWARD

            - name: SCHEMA_REGISTRY_HEAP_OPTS
              value: -Xms256m -Xmx512m

          startupProbe:
            httpGet:
              path: /subjects
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /subjects
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /subjects
              port: http
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6

          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
