apiVersion: v1
kind: Pod

metadata:
  name: expose-pod-information
  namespace: default

spec:
  containers:
    - name: main-container
      image: nginx:1.20
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "0.5"
          memory: 256Mi
        requests:
          cpu: "0.1"
          memory: 128Mi
    - name: sidecar-container
      image: busybox:1.28
      command: ["sh", "-c"]
      args:
        - |
          while true; do
            echo "Pod Information:";
            echo "Pod Name: $POD_NAME";
            echo "Pod Namespace: $POD_NAMESPACE";
            echo "Pod IP: $POD_IP";
            echo "Node Name: $NODE_NAME";
            echo "Node IP: $NODE_IP";
            sleep 20;
          done
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      resources:
        limits:
          cpu: "0.5"
          memory: 256Mi
        requests:
          cpu: "0.1"
          memory: 128Mi
